"""empty message

Revision ID: 14b330f5a32f
Revises: 03eac68401f0
Create Date: 2020-05-18 12:09:23.829986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b330f5a32f'
down_revision = '03eac68401f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('current_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'current_date')
    # ### end Alembic commands ###
