"""empty message

Revision ID: 9459631da55e
Revises: 
Create Date: 2020-05-13 15:07:59.969273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9459631da55e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('qualification', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=140), nullable=True),
    sa.Column('consultation_fees', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=True),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address_line_1', sa.Text(), nullable=False),
    sa.Column('address_line_2', sa.Text(), nullable=False),
    sa.Column('address_line_3', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('speciality', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_no', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('hosp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hosp_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relate',
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], )
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morning_slots', sa.Text(), nullable=True),
    sa.Column('afternoon_slots', sa.Text(), nullable=True),
    sa.Column('evening_slots', sa.Text(), nullable=True),
    sa.Column('night_slots', sa.Text(), nullable=True),
    sa.Column('hospital_name', sa.String(length=20), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    op.drop_table('reviews')
    op.drop_table('relate')
    op.drop_table('feedback')
    op.drop_table('hospital')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
